// Hindi translations. Key = exact English text shown in the app, value = Hindi.
// To translate a new line, add one entry here; anything not listed stays in English.
// Short common terms (GST, GSTIN, CGST, SGST, IGST, UPI, PDF, CRM, SKU) are kept as they are.
const hi = {
  "(Best Value)": "(सबसे किफायती)", "(optional)": "(वैकल्पिक)", "+ Add Member": "+ सदस्य जोड़ें",
  "+ Add New Client": "+ नया क्लाइंट जोड़ें", "+ Add New Lead": "+ नया लीड जोड़ें", "+ Add line": "+ लाइन जोड़ें",
  "+ Create New Invoice": "+ नया इनवॉइस बनाएं", "+ Create New Quotation": "+ नया कोटेशन बनाएं", "+ Manage Stock": "+ स्टॉक संभालें",
  "+ New Invoice": "+ नया इनवॉइस", "+ Record New Purchase": "+ नई खरीद दर्ज करें", "/ month": "/ माह",
  "14-day full-feature free trial": "14 दिन का फ्री ट्रायल", "24/7 Support Assistant": "24/7 सहायता",
  "3 days overdue": "3 दिन देर से", "7 days overdue": "7 दिन देर से",
  "A timeline of your recent actions in this workspace.": "इस वर्कस्पेस में आपकी हाल की गतिविधियाँ।",
  "About Plivex": "Plivex के बारे में", "Access Restricted": "पहुँच प्रतिबंधित", "Access Restricted by Admin": "एडमिन ने पहुँच रोकी है",
  "Account activity": "खाता गतिविधि", "Account profile": "खाता प्रोफ़ाइल", "Accountant / CA": "अकाउंटेंट / सीए", "Accountants": "अकाउंटेंट",
  "Actions": "कार्य", "Active Leads": "सक्रिय लीड", "Add New Team Member": "नया टीम सदस्य जोड़ें", "Add Stock": "स्टॉक जोड़ें",
  "Add a UPI QR code": "UPI QR कोड जोड़ें", "Add client": "क्लाइंट जोड़ें", "Add line item": "आइटम जोड़ें", "Add line items": "आइटम जोड़ें",
  "Add new lead": "नया लीड जोड़ें", "Add product": "प्रोडक्ट जोड़ें", "Add service": "सेवा जोड़ें", "Add your business details": "अपने व्यवसाय की जानकारी भरें",
  "Add your details once to auto-fill every invoice, quote and report.": "अपनी जानकारी एक बार भरें, हर इनवॉइस और रिपोर्ट में अपने आप आ जाएगी।",
  "Address": "पता", "Address:": "पता:", "Admin Note": "एडमिन नोट", "All Invoices": "सभी इनवॉइस", "All categories": "सभी श्रेणियाँ",
  "All invoices": "सभी इनवॉइस", "All status": "सभी स्थिति", "All time": "अब तक", "All workspace pages": "वर्कस्पेस के सभी पेज",
  "Amount": "राशि", "Amount (₹)": "राशि (₹)",
  "An invite email will be sent so they can join this workspace with the assigned role.": "उन्हें निमंत्रण ईमेल भेजा जाएगा ताकि वे तय भूमिका के साथ वर्कस्पेस से जुड़ सकें।",
  "Apply discount & tax": "छूट और टैक्स लगाएं", "Auto Reminder": "ऑटो रिमाइंडर", "Auto-Matched": "अपने आप मिलान हुआ",
  "Auto-Reminder & Email Settings": "ऑटो-रिमाइंडर और ईमेल सेटिंग", "Auto-match": "ऑटो-मिलान", "Autosaved": "अपने आप सेव हुआ",
  "Average invoice": "औसत इनवॉइस", "Back to Plivex": "Plivex पर वापस", "Back to app": "ऐप पर वापस", "Back to log in": "लॉग इन पर वापस",
  "Bank Transfer": "बैंक ट्रांसफर", "Bank account": "बैंक खाता", "Basic": "बेसिक", "Basic Monthly": "बेसिक मासिक", "Basic Yearly": "बेसिक वार्षिक",
  "Basic details": "बुनियादी जानकारी", "Basic plan": "बेसिक प्लान", "Bill clients with GST-ready, print-perfect PDFs in under a minute.": "GST-तैयार, साफ़ PDF इनवॉइस एक मिनट से कम में बनाएं।",
  "Bill details": "बिल की जानकारी", "Billing / Sales": "बिलिंग / सेल्स", "Billing Executive / Sales": "बिलिंग एग्ज़ीक्यूटिव / सेल्स", "Billing, without the drag.": "बिलिंग, बिना झंझट के।",
  "Breakdown of CGST, SGST and IGST collected.": "वसूले गए CGST, SGST और IGST का ब्योरा।", "Browse the help center": "सहायता केंद्र देखें",
  "Business": "बिज़नेस", "Business address": "व्यवसाय का पता", "Business name": "व्यवसाय का नाम", "Business profile": "बिज़नेस प्रोफ़ाइल",
  "CGST + SGST": "CGST + SGST", "CGST collected": "वसूला गया CGST", "Call support": "सहायता को कॉल करें", "Cancel": "रद्द करें", "Cancelled": "रद्द",
  "Card": "कार्ड", "Cash": "नकद", "Category": "श्रेणी", "Changes save automatically": "बदलाव अपने आप सेव होते हैं", "Check your email": "अपना ईमेल देखें",
  "Check your inbox for a new confirmation link.": "नए पुष्टि लिंक के लिए अपना इनबॉक्स देखें।", "Cheque": "चेक", "Choose File": "फ़ाइल चुनें",
  "Choose your subscription": "अपना प्लान चुनें", "Clear": "साफ़ करें", "Clear canvas": "कैनवास साफ़ करें", "Client": "क्लाइंट",
  "Client & Contact Management": "क्लाइंट और संपर्क प्रबंधन", "Client Business Name": "क्लाइंट का व्यवसाय नाम", "Client Business Name (required)": "क्लाइंट का व्यवसाय नाम (ज़रूरी)",
  "Client CRM": "क्लाइंट CRM", "Client WhatsApp Number": "क्लाइंट का WhatsApp नंबर", "Client address": "क्लाइंट का पता", "Client database": "क्लाइंट डेटाबेस",
  "Client details": "क्लाइंट की जानकारी", "Client directory and lead pipeline in one place.": "क्लाइंट सूची और लीड पाइपलाइन एक जगह।", "Client email": "क्लाइंट का ईमेल",
  "Client name": "क्लाइंट का नाम", "Clients": "क्लाइंट", "Clients Directory": "क्लाइंट सूची", "Close": "बंद करें", "Close pricing": "प्लान बंद करें",
  "Company": "कंपनी", "Company (optional)": "कंपनी (वैकल्पिक)", "Company name (optional)": "कंपनी का नाम (वैकल्पिक)", "Complete Your Business Profile": "अपनी बिज़नेस प्रोफ़ाइल पूरी करें",
  "Confirm Password": "पासवर्ड दोबारा लिखें", "Contact": "संपर्क", "Contact Plivex Support": "Plivex सहायता से संपर्क करें", "Contact Us": "हमसे संपर्क करें",
  "Contact the app administrator for access": "पहुँच के लिए ऐप एडमिन से संपर्क करें", "Control which cards team members see on their dashboard.": "तय करें कि टीम सदस्यों को डैशबोर्ड पर कौन से कार्ड दिखें।",
  "Convert": "बदलें", "Copy invite link": "निमंत्रण लिंक कॉपी करें", "Copy user ID": "यूज़र आईडी कॉपी करें", "Could not save your change": "आपका बदलाव सेव नहीं हो सका",
  "Create Invoice": "इनवॉइस बनाएं", "Create one": "नया बनाएं", "Create your account": "अपना खाता बनाएं", "Create your free workspace — 14-day full trial": "अपना फ्री वर्कस्पेस बनाएं — 14 दिन का ट्रायल",
  "Creating account...": "खाता बन रहा है...", "Currency": "मुद्रा", "Current Plan": "वर्तमान प्लान", "DRAFT": "ड्राफ़्ट", "Dark theme": "डार्क थीम", "Dashboard": "डैशबोर्ड",
  "Data Import / Export": "डेटा इम्पोर्ट / एक्सपोर्ट", "Date": "तारीख", "Default GST rate": "डिफ़ॉल्ट GST दर", "Default currency": "डिफ़ॉल्ट मुद्रा", "Default logo": "डिफ़ॉल्ट लोगो",
  "Default note": "डिफ़ॉल्ट नोट", "Default terms": "डिफ़ॉल्ट शर्तें", "Defaults applied across your workspace.": "आपके पूरे वर्कस्पेस पर लागू डिफ़ॉल्ट।", "Delete": "हटाएं",
  "Delete invoice": "इनवॉइस हटाएं", "Delete line item": "आइटम हटाएं", "Delete member": "सदस्य हटाएं", "Delete product": "प्रोडक्ट हटाएं", "Description": "विवरण",
  "Discount": "छूट", "Dismiss": "बंद करें", "Display name": "प्रदर्शित नाम", "Done": "हो गया", "Download & share": "डाउनलोड और शेयर", "Download PDF": "PDF डाउनलोड करें",
  "Download all sales and expense records as a CSV file.": "बिक्री और खर्च के सभी रिकॉर्ड CSV फ़ाइल में डाउनलोड करें।", "Due date": "देय तारीख", "Duplicate line item": "आइटम की कॉपी बनाएं",
  "Edit": "बदलें", "Edit invoice": "इनवॉइस बदलें", "Edit product": "प्रोडक्ट बदलें", "Edit role": "भूमिका बदलें", "Email": "ईमेल", "Email address": "ईमेल पता", "Email sent": "ईमेल भेजा गया",
  "Email support": "ईमेल सहायता", "Email support · 24/7": "ईमेल सहायता · 24/7", "Enjoy 14 days of free Basic plan access 👋": "14 दिन बेसिक प्लान मुफ़्त में चलाएं 👋",
  "Enter Client's WhatsApp Number": "क्लाइंट का WhatsApp नंबर लिखें", "Enter a recipient email to send a test reminder.": "टेस्ट रिमाइंडर भेजने के लिए ईमेल पता लिखें।",
  "Enter address (optional)": "पता लिखें (वैकल्पिक)", "Enter your new password below": "नीचे अपना नया पासवर्ड लिखें", "Enterprise Yearly": "एंटरप्राइज़ वार्षिक",
  "Enterprise billing": "एंटरप्राइज़ बिलिंग", "Enterprise features": "एंटरप्राइज़ सुविधाएँ", "Estimated value (₹)": "अनुमानित मूल्य (₹)", "Every module unlocked": "हर सुविधा खुली",
  "Exit Workspace": "वर्कस्पेस छोड़ें", "Expand": "बड़ा करें", "Expenses": "खर्च", "Expires": "समाप्ति", "Export CSV": "CSV एक्सपोर्ट", "Export GST": "GST एक्सपोर्ट",
  "Export GSTR-1 JSON": "GSTR-1 JSON एक्सपोर्ट", "Export all data (JSON)": "सारा डेटा एक्सपोर्ट करें (JSON)", "Export your books": "अपना हिसाब-किताब एक्सपोर्ट करें",
  "FAQs & Guides": "सवाल-जवाब और गाइड", "Failed": "विफल", "Fill client information": "क्लाइंट की जानकारी भरें", "Finish setup": "सेटअप पूरा करें", "First invoice": "पहला इनवॉइस",
  "Flat discount (₹)": "तय छूट (₹)", "Forgot password?": "पासवर्ड भूल गए?", "Free Trial": "फ्री ट्रायल", "Free trial ended · choose a plan to continue": "फ्री ट्रायल खत्म · जारी रखने के लिए प्लान चुनें",
  "Free workspace": "फ्री वर्कस्पेस", "Fresh invoice started": "नया इनवॉइस शुरू हुआ", "From": "से", "From date": "शुरू की तारीख", "Full GST compliance (GSTR-1/3B, Tally)": "पूरा GST अनुपालन (GSTR-1/3B, Tally)",
  "GST breakdown": "GST का ब्योरा", "GST rate": "GST दर", "GST-ready, print-perfect PDFs in under a minute.": "GST-तैयार, साफ़ PDF एक मिनट से कम में।",
  "GSTR-1 registers and Tally-ready exports.": "GSTR-1 रजिस्टर और Tally के लिए तैयार एक्सपोर्ट।", "Generating your invoice PDF…": "आपका इनवॉइस PDF बन रहा है…",
  "Get Premium": "प्रीमियम लें", "Get started free": "मुफ़्त शुरू करें", "Getting started": "शुरुआत करें", "Go Home": "होम जाएं", "Have a Workspace Invite Code?": "वर्कस्पेस का निमंत्रण कोड है?",
  "Help & Support": "मदद और सहायता", "Help center": "सहायता केंद्र", "IGST collected": "वसूला गया IGST", "If an account exists with that email, you'll receive a password reset link shortly.": "अगर इस ईमेल से खाता है, तो आपको जल्द ही पासवर्ड रीसेट लिंक मिलेगा।",
  "If you believe this is an error, you can:": "अगर आपको लगता है कि यह गलती है, तो आप:", "Import target": "इम्पोर्ट का प्रकार", "In stock": "स्टॉक में",
  "Include a country code if the number is outside India.": "नंबर भारत से बाहर का हो तो देश कोड जोड़ें।", "Invalid reset link": "रीसेट लिंक सही नहीं है",
  "Inventory auto-deducts on every bill you raise.": "हर बिल पर स्टॉक अपने आप कम होता है।", "Invite code": "निमंत्रण कोड", "Invite teammates and control what each role can access.": "टीम को जोड़ें और तय करें कि हर भूमिका क्या देख सकती है।",
  "Invite your staff and control what each role can see and do.": "अपने स्टाफ को जोड़ें और तय करें कि हर भूमिका क्या देख और कर सकती है।", "Invoice": "इनवॉइस", "Invoice design": "इनवॉइस डिज़ाइन", "Invoice desk": "इनवॉइस डेस्क",
  "Invoice history": "इनवॉइस इतिहास", "Invoice no.": "इनवॉइस नं.", "Invoice settings": "इनवॉइस सेटिंग", "Invoices": "इनवॉइस", "Invoices this month": "इस माह के इनवॉइस", "Issue date": "जारी करने की तारीख",
  "Item name — type to search HSN": "आइटम का नाम — HSN खोजने के लिए लिखें", "Items": "आइटम", "Join another workspace": "दूसरे वर्कस्पेस से जुड़ें", "Last month": "पिछला माह",
  "Lead Management": "लीड प्रबंधन", "Lead Tracker": "लीड ट्रैकर", "Lead name": "लीड का नाम", "Legal": "कानूनी", "Let's go 🚀": "चलिए शुरू करें 🚀", "Line items": "आइटम",
  "Linked": "जुड़ा हुआ", "Live Staff Presence": "स्टाफ की लाइव मौजूदगी", "Live business command center — exclusive to the Business Owner.": "लाइव बिज़नेस कमांड सेंटर — सिर्फ़ मालिक के लिए।",
  "Live demo preview": "लाइव डेमो प्रीव्यू", "Live preview": "लाइव प्रीव्यू", "Loading staff presence…": "स्टाफ की मौजूदगी लोड हो रही है…", "Loading today's activity…": "आज की गतिविधि लोड हो रही है…",
  "Log a payment": "भुगतान दर्ज करें", "Log in": "लॉग इन", "Log in to your account": "अपने खाते में लॉग इन करें", "Log out": "लॉग आउट", "Log payment": "भुगतान दर्ज करें", "Logging in...": "लॉग इन हो रहा है...",
  "Low Stock Alert": "कम स्टॉक चेतावनी", "Low Stock Alerts": "कम स्टॉक चेतावनियाँ", "Make it official": "इसे पक्का करें", "Make it official.": "इसे पक्का करें।", "Manage card visibility": "कार्ड दिखाना तय करें",
  "Manage products and watch quantities auto-deduct on every invoice.": "प्रोडक्ट संभालें, हर इनवॉइस पर मात्रा अपने आप घटेगी।", "Manager": "मैनेजर", "Managers": "मैनेजर", "Map columns": "कॉलम मिलाएं", "Maybe later": "बाद में",
  "Member email address (required)": "सदस्य का ईमेल पता (ज़रूरी)", "Member name": "सदस्य का नाम", "Method": "तरीका", "Monthly Expense": "मासिक खर्च", "Monthly Sales": "मासिक बिक्री", "More": "और",
  "Move leads from new to won and never miss a follow-up.": "लीड को नए से जीत तक ले जाएं, कोई फ़ॉलो-अप न छूटे।", "Name": "नाम", "Net Profit": "शुद्ध मुनाफ़ा", "New Password": "नया पासवर्ड", "New invoice": "नया इनवॉइस",
  "New password": "नया पासवर्ड", "New quotation": "नया कोटेशन", "New template": "नया टेम्पलेट", "New to Plivex?": "Plivex पर नए हैं?", "Next": "अगला", "No card required": "कार्ड की ज़रूरत नहीं",
  "No activity recorded yet. Generate or share an invoice to get started.": "अभी कोई गतिविधि नहीं। शुरू करने के लिए इनवॉइस बनाएं या शेयर करें।", "No charge was made. You can try again.": "कोई पैसा नहीं कटा। आप दोबारा कोशिश कर सकते हैं।",
  "No clients match your search. Add a client to invoice them in one click.": "खोज से कोई क्लाइंट नहीं मिला। क्लाइंट जोड़ें और एक क्लिक में इनवॉइस बनाएं।", "No clients saved yet. Add your first client to speed up invoicing.": "अभी कोई क्लाइंट सेव नहीं है। पहला क्लाइंट जोड़ें।",
  "No expenses match your filters.": "फ़िल्टर से कोई खर्च नहीं मिला।", "No invoices generated this month yet.": "इस माह अभी कोई इनवॉइस नहीं बना।", "No invoices raised for this client yet.": "इस क्लाइंट के लिए अभी कोई इनवॉइस नहीं।",
  "No item breakdown stored.": "आइटम का ब्योरा सेव नहीं है।", "No leads": "कोई लीड नहीं", "No logo": "लोगो नहीं", "No other bills from this vendor.": "इस विक्रेता का कोई और बिल नहीं।", "No payments logged yet.": "अभी कोई भुगतान दर्ज नहीं।",
  "No payments recorded yet.": "अभी कोई भुगतान दर्ज नहीं।", "No products in stock yet. Add your first product to enable auto-deduction on invoices.": "अभी स्टॉक में कोई प्रोडक्ट नहीं। पहला प्रोडक्ट जोड़ें ताकि इनवॉइस पर स्टॉक अपने आप घटे।",
  "No saved invoices yet. Generate and download an invoice from the desk to see it here.": "अभी कोई इनवॉइस सेव नहीं। डेस्क से इनवॉइस बनाकर डाउनलोड करें, यहाँ दिखेगा।", "No services saved yet.": "अभी कोई सेवा सेव नहीं।",
  "No staff actions recorded today yet.": "आज अभी कोई स्टाफ गतिविधि नहीं।", "No staff invites": "कोई स्टाफ निमंत्रण नहीं", "No staff presence yet — activity appears as your team uses the workspace.": "अभी कोई स्टाफ मौजूद नहीं — टीम के इस्तेमाल करते ही गतिविधि दिखेगी।",
  "No team members yet. Add your first teammate to get started.": "अभी कोई टीम सदस्य नहीं। पहला सदस्य जोड़ें।", "No templates yet. Create one for recurring invoice layouts.": "अभी कोई टेम्पलेट नहीं। बार-बार भेजे जाने वाले इनवॉइस के लिए बनाएं।",
  "Note to client": "क्लाइंट के लिए नोट", "Note:": "नोट:", "Notes": "नोट", "Notes & terms": "नोट और शर्तें", "Number": "संख्या", "On due date": "देय तारीख पर", "On due date + 3 days overdue": "देय तारीख पर + 3 दिन देर होने पर",
  "Open CRM": "CRM खोलें", "Open Settings": "सेटिंग खोलें", "Open invoice builder": "इनवॉइस बिल्डर खोलें", "Optional note for the client": "क्लाइंट के लिए वैकल्पिक नोट", "Optional reference / bill no.": "वैकल्पिक संदर्भ / बिल नं.",
  "Optional · shown on the final page": "वैकल्पिक · आख़िरी पेज पर दिखेगा", "Order status": "ऑर्डर की स्थिति", "Overdue": "देर से", "Owner": "मालिक", "Owner Master Control": "मालिक का मास्टर कंट्रोल", "Owner · Locked": "मालिक · लॉक",
  "Owners": "मालिक", "PDF export failed. Please try again.": "PDF नहीं बन सका। कृपया दोबारा कोशिश करें।", "PRO": "प्रो", "Page Not Found": "पेज नहीं मिला", "Paid": "भुगतान हुआ", "Password": "पासवर्ड",
  "Payment Reconciliation Engine": "भुगतान मिलान", "Payment failed": "भुगतान विफल", "Payment history": "भुगतान इतिहास", "Payment logs": "भुगतान लॉग", "Payment not verified": "भुगतान की पुष्टि नहीं हुई", "Payment successful": "भुगतान सफल",
  "Payment terms": "भुगतान की शर्तें", "Payments & Financial Tracking": "भुगतान और वित्तीय ट्रैकिंग", "Pending": "बकाया", "Pending Payments": "बकाया भुगतान", "Percentage discount (%)": "प्रतिशत छूट (%)", "Phone": "फ़ोन", "Phone support": "फ़ोन सहायता",
  "Phone support · Mon–Sat": "फ़ोन सहायता · सोम–शनि", "Pipeline Value": "पाइपलाइन मूल्य", "Please complete all required invoice details before sharing on WhatsApp": "WhatsApp पर भेजने से पहले इनवॉइस की सारी ज़रूरी जानकारी भरें",
  "Please enter a valid 10-digit WhatsApp number.": "कृपया 10 अंकों का सही WhatsApp नंबर लिखें।", "Please fill all required fields before generating the invoice.": "इनवॉइस बनाने से पहले सभी ज़रूरी जानकारी भरें।", "Plivex Premium": "Plivex प्रीमियम",
  "Plivex Pro": "Plivex प्रो", "Plivex · Made in India 🇮🇳": "Plivex · भारत में बना 🇮🇳", "Pre-filled designs for invoices you send often.": "बार-बार भेजे जाने वाले इनवॉइस के लिए तैयार डिज़ाइन।", "Premium plan": "प्रीमियम प्लान", "Prev": "पिछला",
  "Preview": "प्रीव्यू", "Preview is still loading. Try again in a moment.": "प्रीव्यू अभी लोड हो रहा है। थोड़ी देर बाद कोशिश करें।", "Price (₹)": "कीमत (₹)", "Prices in INR · GST applicable · Secure checkout via PayU": "कीमतें ₹ में · GST लागू · PayU से सुरक्षित भुगतान",
  "Pricing": "कीमत", "Pricing & exports": "कीमत और एक्सपोर्ट", "Pricing Plans": "प्लान और कीमत", "Pricing plans": "प्लान और कीमत", "Primary": "मुख्य", "Privacy": "गोपनीयता", "Privacy Policy": "गोपनीयता नीति", "Pro": "प्रो", "Pro Monthly": "प्रो मासिक",
  "Pro plan active": "प्रो प्लान चालू है", "Processing transactions…": "लेन-देन प्रोसेस हो रहे हैं…", "Product": "प्रोडक्ट", "Product name": "प्रोडक्ट का नाम", "Profile updated": "प्रोफ़ाइल अपडेट हुई", "Purchase": "खरीद", "Qty": "मात्रा", "Quantity": "मात्रा",
  "Quick actions": "तेज़ कार्य", "Quick templates": "तेज़ टेम्पलेट", "Quotations": "कोटेशन", "Rate": "दर", "Rate (₹)": "दर (₹)", "Rate or amount": "दर या राशि", "Ready to send": "भेजने के लिए तैयार", "Received": "प्राप्त", "Reconcile": "मिलान करें",
  "Reconciled": "मिलान हो गया", "Record a purchase": "खरीद दर्ज करें", "Record purchase": "खरीद दर्ज करें", "Refund": "रिफ़ंड", "Refund & Cancellation Policy": "रिफ़ंड और रद्द करने की नीति", "Refund Policy": "रिफ़ंड नीति",
  "Registered business address": "पंजीकृत व्यवसाय का पता", "Reminder interval days": "रिमाइंडर के बीच के दिन", "Reminder schedule": "रिमाइंडर का समय", "Remove logo": "लोगो हटाएं", "Reports": "रिपोर्ट", "Reports & Business Intelligence": "रिपोर्ट और बिज़नेस जानकारी",
  "Request a new link": "नया लिंक मंगाएं", "Requirement": "ज़रूरत", "Resend": "दोबारा भेजें", "Reset": "रीसेट", "Reset password": "पासवर्ड रीसेट करें", "Resetting...": "रीसेट हो रहा है...", "Reuse client details across invoices in a couple of taps.": "क्लाइंट की जानकारी बार-बार इस्तेमाल करें।",
  "Revenue": "आमदनी", "Role": "भूमिका", "Role permissions": "भूमिका की अनुमतियाँ", "Run your entire billing business from one dashboard.": "अपनी पूरी बिलिंग एक ही डैशबोर्ड से चलाएं।", "SGST collected": "वसूला गया SGST", "Sales": "बिक्री", "Sample data": "नमूना डेटा",
  "Save client": "क्लाइंट सेव करें", "Save client details once and reuse them forever across invoices.": "क्लाइंट की जानकारी एक बार सेव करें, हमेशा इस्तेमाल करें।", "Save lead": "लीड सेव करें", "Save log": "लॉग सेव करें", "Save product": "प्रोडक्ट सेव करें",
  "Save purchase": "खरीद सेव करें", "Save quotation": "कोटेशन सेव करें", "Save recurring services with preset prices for faster invoicing.": "बार-बार वाली सेवाएँ तय कीमत के साथ सेव करें।", "Save service": "सेवा सेव करें", "Save template": "टेम्पलेट सेव करें",
  "Saved automatically": "अपने आप सेव हुआ", "Saved defaults pulled in when you start a new invoice.": "नया इनवॉइस शुरू करने पर सेव किए डिफ़ॉल्ट आ जाते हैं।", "Saved locally": "इसी डिवाइस पर सेव", "Search client, invoice no…": "क्लाइंट, इनवॉइस नं. खोजें…",
  "Search clients…": "क्लाइंट खोजें…", "Search products…": "प्रोडक्ट खोजें…", "Search vendor, category…": "विक्रेता, श्रेणी खोजें…", "Select account": "खाता चुनें", "Select role": "भूमिका चुनें", "Send a test reminder": "टेस्ट रिमाइंडर भेजें",
  "Send estimates clients can approve, then convert to invoices in one click.": "क्लाइंट को कोटेशन भेजें, मंज़ूरी के बाद एक क्लिक में इनवॉइस बनाएं।", "Send payment reminder": "भुगतान रिमाइंडर भेजें", "Send reminder": "रिमाइंडर भेजें", "Sending...": "भेजा जा रहा है...",
  "Service catalog": "सेवा सूची", "Service name": "सेवा का नाम", "Settings": "सेटिंग", "Share": "शेयर", "Share this workspace invite token if the email doesn't arrive:": "ईमेल न पहुँचे तो यह वर्कस्पेस निमंत्रण कोड खुद भेजें:", "Shipping": "शिपिंग",
  "Shipping / handling (₹)": "शिपिंग / हैंडलिंग (₹)", "Sign in": "साइन इन", "Sign in to continue Plivex": "Plivex जारी रखने के लिए साइन इन करें", "Sign in to try": "आज़माने के लिए साइन इन करें", "Sign once, send with confidence.": "एक बार साइन करें, भरोसे से भेजें।",
  "Sign out": "साइन आउट", "Sign up to get started": "शुरू करने के लिए साइन अप करें", "Signature": "हस्ताक्षर", "Signature block": "हस्ताक्षर की जगह", "Signature saved": "हस्ताक्षर सेव हुआ", "Simple, honest pricing for every business.": "हर व्यवसाय के लिए सीधी और ईमानदार कीमत।",
  "Single-user billing": "एक यूज़र की बिलिंग", "Smart Billing & Invoicing": "स्मार्ट बिलिंग और इनवॉइसिंग", "Staff members": "स्टाफ सदस्य", "Start free": "मुफ़्त शुरू करें", "Start free for 14 days with every feature unlocked. No card required. Cancel anytime.": "14 दिन मुफ़्त शुरू करें। कार्ड की ज़रूरत नहीं। कभी भी रद्द करें।",
  "Started": "शुरू हुआ", "Status": "स्थिति", "Step-by-step guides to breeze through your billing.": "बिलिंग आसान करने के लिए स्टेप-बाई-स्टेप गाइड।", "Stock": "स्टॉक", "Stock / Products": "स्टॉक / प्रोडक्ट", "Stock Inventory": "स्टॉक सूची", "Stock Items": "स्टॉक आइटम",
  "Store Keeper / Inventory": "स्टोरकीपर / इन्वेंटरी", "Store Keepers": "स्टोरकीपर", "Subtotal": "उप-योग", "Support chat": "सहायता चैट", "Support hours: Monday–Saturday, 10:00–19:00 IST.": "सहायता का समय: सोमवार–शनिवार, सुबह 10 से शाम 7 (IST)।",
  "Tap any module to sign in and land exactly where you wanted to go.": "किसी भी विकल्प पर टैप करें, साइन इन के बाद सीधे वहीं पहुँचेंगे।", "Tax & discount": "टैक्स और छूट", "Tax mode": "टैक्स का तरीका", "Tax summary": "टैक्स सारांश", "Team": "टीम", "Team Management": "टीम प्रबंधन", "Team Members": "टीम सदस्य",
  "Template name": "टेम्पलेट का नाम", "Terms": "शर्तें", "Terms & conditions": "नियम और शर्तें", "Terms:": "शर्तें:", "The fast billing desk": "तेज़ बिलिंग डेस्क", "The invoice could not be saved. Please try again.": "इनवॉइस सेव नहीं हो सका। कृपया दोबारा कोशिश करें।",
  "The link you used appears to be incomplete. Please request a new password reset email.": "आपका लिंक अधूरा लगता है। कृपया नया पासवर्ड रीसेट ईमेल मंगाएं।", "This month": "इस माह", "This password reset link is missing or invalid": "यह पासवर्ड रीसेट लिंक गायब या गलत है", "This window stays open until you upgrade.": "यह विंडो अपग्रेड करने तक खुली रहेगी।",
  "To": "तक", "To date": "अंतिम तारीख", "Today's Sales Activity": "आज की बिक्री गतिविधि", "Toggle dark mode": "डार्क मोड बदलें", "Toggle the workspace appearance.": "वर्कस्पेस का रंग बदलें।", "Total": "कुल", "Total Clients": "कुल क्लाइंट", "Total Expenses": "कुल खर्च",
  "Total Invoiced": "कुल इनवॉइस राशि", "Total Products": "कुल प्रोडक्ट", "Total Revenue Generated": "कुल आमदनी", "Total billed": "कुल बिल", "Total members": "कुल सदस्य", "Total tax": "कुल टैक्स", "Track payments received and outstanding.": "प्राप्त और बकाया भुगतान देखें।",
  "Track vendor bills and purchases to see your real net profit.": "विक्रेता के बिल और खरीद दर्ज करें, असली मुनाफ़ा देखें।", "Transaction Results": "लेन-देन के नतीजे", "Try again": "दोबारा कोशिश करें", "Try it yourself — one tap away": "खुद आज़माएं — बस एक टैप दूर", "Try logging out and back in again": "लॉग आउट करके दोबारा लॉग इन करें",
  "Type signature": "हस्ताक्षर लिखें", "UPI ID / VPA": "UPI आईडी / VPA", "Unique User ID": "यूनिक यूज़र आईडी", "Unit": "इकाई", "Units in Stock": "स्टॉक में इकाइयाँ", "Unlock GSTR-1 Export": "GSTR-1 एक्सपोर्ट खोलें", "Unlock Multi-Currency": "मल्टी-करेंसी खोलें", "Unmatched": "मिलान नहीं हुआ",
  "Unpaid": "अदा नहीं हुआ", "Update failed": "अपडेट नहीं हो सका", "Upload CSV Bank Statement": "बैंक स्टेटमेंट CSV अपलोड करें", "Upload a CSV bank statement to auto-match transactions with pending invoices": "बैंक स्टेटमेंट CSV अपलोड करें, बकाया इनवॉइस से लेन-देन अपने आप मिलेंगे", "Upload failed": "अपलोड नहीं हो सका",
  "Upload signature": "हस्ताक्षर अपलोड करें", "Usage reports": "उपयोग रिपोर्ट", "Use signature": "हस्ताक्षर इस्तेमाल करें", "Use template": "टेम्पलेट इस्तेमाल करें", "Vendor": "विक्रेता", "Vendor / supplier": "विक्रेता / सप्लायर", "Vendor name": "विक्रेता का नाम", "Verify you are logged in with the correct account": "जाँचें कि आप सही खाते से लॉग इन हैं",
  "View": "देखें", "View invoice": "इनवॉइस देखें", "We could not confirm this payment. Contact support if you were charged.": "हम इस भुगतान की पुष्टि नहीं कर सके। पैसे कटे हों तो सहायता से संपर्क करें।", "We typically reply in minutes": "हम आम तौर पर कुछ मिनट में जवाब देते हैं", "We usually reply within a few hours.": "हम आम तौर पर कुछ घंटों में जवाब देते हैं।",
  "Welcome to Plivex": "Plivex में आपका स्वागत है", "What do they need?": "उन्हें क्या चाहिए?", "Workspace": "वर्कस्पेस", "Workspace defaults, team roles and branding.": "वर्कस्पेस के डिफ़ॉल्ट, टीम की भूमिकाएँ और ब्रांडिंग।", "Workspace manager": "वर्कस्पेस मैनेजर", "Workspace membership": "वर्कस्पेस सदस्यता",
  "Workspace settings": "वर्कस्पेस सेटिंग", "Your 14-day free trial has ended": "आपका 14 दिन का फ्री ट्रायल खत्म हो गया", "Your Business Name": "आपके व्यवसाय का नाम", "Your Business Name (required)": "आपके व्यवसाय का नाम (ज़रूरी)", "Your GSTIN": "आपका GSTIN", "Your UPI ID / VPA": "आपकी UPI आईडी / VPA", "Your business": "आपका व्यवसाय",
  "Your current plan": "आपका वर्तमान प्लान", "Your name": "आपका नाम", "Your next professional invoice is already taking shape.": "आपका अगला प्रोफ़ेशनल इनवॉइस तैयार हो रहा है।", "Your plan": "आपका प्लान", "Your premium plan is now active.": "आपका प्रीमियम प्लान अब चालू है।", "draft": "ड्राफ़्ट", "failed": "विफल", "just now": "अभी", "paid": "भुगतान हुआ",
  "pending": "बकाया", "units": "इकाइयाँ", "— skip —": "— छोड़ें —", "← Dashboard": "← डैशबोर्ड", "← Invoice desk": "← इनवॉइस डेस्क",
  // Language chooser and landing page
  "Language": "भाषा", "Available in Hindi and English": "हिंदी और English में उपलब्ध", "Hindi": "हिंदी", "English": "English",
  "Choose the language of the app. You can change it any time in Settings.": "ऐप की भाषा चुनें। आप इसे कभी भी सेटिंग में बदल सकते हैं।",
  "Isolated workspace security": "अलग-अलग वर्कस्पेस की सुरक्षा", "Role-based access control": "भूमिका के हिसाब से पहुँच", "Audit activity logs": "गतिविधि का रिकॉर्ड", "Mobile responsive PWA": "मोबाइल पर चलने वाला ऐप",
  "Multi-user team access": "टीम के कई सदस्यों की पहुँच", "Custom branding & logos": "अपनी ब्रांडिंग और लोगो", "Bulk PDF export": "कई PDF एक साथ", "Enterprise features": "एंटरप्राइज़ सुविधाएँ", "Core pillars": "मुख्य स्तंभ", "First invoice": "पहला इनवॉइस",
  "Usability & Integrations": "उपयोग और इंटीग्रेशन", "AI-First Infrastructure & Security": "सुरक्षित और भरोसेमंद ढाँचा", "Ultra-affordable, fast, AI-first B2B SaaS.": "बेहद किफायती और तेज़ बिलिंग सॉफ़्टवेयर।",
};
export default hi;
